// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/5/11 23:44:38
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/kasugano/Documents/matsu_rip/nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kasugano/Documents/matsu_rip/nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kasugano/Documents/matsu_rip/nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kasugano/Documents/matsu_rip/nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kasugano/Documents/matsu_rip/nuxt/plugins/**/*.{js,ts,mjs}","/Users/kasugano/Documents/matsu_rip/nuxt/composables/**/*.{js,ts,mjs}","/Users/kasugano/Documents/matsu_rip/nuxt/utils/**/*.{js,ts,mjs}","/Users/kasugano/Documents/matsu_rip/nuxt/pages/index.vue","/Users/kasugano/Documents/matsu_rip/nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kasugano/Documents/matsu_rip/nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kasugano/Documents/matsu_rip/nuxt/app.config.{js,ts,mjs}","/Users/kasugano/Documents/matsu_rip/nuxt/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;