// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/15/2025, 7:07:28 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/kasugano/Documents/matsu_rip/nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kasugano/Documents/matsu_rip/nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kasugano/Documents/matsu_rip/nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kasugano/Documents/matsu_rip/nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kasugano/Documents/matsu_rip/nuxt/plugins/**/*.{js,ts,mjs}","/Users/kasugano/Documents/matsu_rip/nuxt/composables/**/*.{js,ts,mjs}","/Users/kasugano/Documents/matsu_rip/nuxt/utils/**/*.{js,ts,mjs}","/Users/kasugano/Documents/matsu_rip/nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kasugano/Documents/matsu_rip/nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kasugano/Documents/matsu_rip/nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kasugano/Documents/matsu_rip/nuxt/app.config.{js,ts,mjs}","/Users/kasugano/Documents/matsu_rip/nuxt/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;